#!/bin/bash

# Create a timestamp for the report
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
OUTPUT_FILE="docs/poetry_environment_report.md"

# Create the report file with a header
cat > $OUTPUT_FILE << EOF
# Poetry Environment Report
**Generated:** $TIMESTAMP

---

## Dependencies
\`\`\`
$(poetry lock 2>&1)
$(poetry install --no-ansi 2>&1)
\`\`\`

## Installed Packages
\`\`\`
$(poetry show)
\`\`\`

## Environment Information
\`\`\`
$(poetry env info)
\`\`\`

## Test Results
\`\`\`
$(poetry run pytest 2>&1)
\`\`\`

## Project Directory Structure
\`\`\`
$(tree --gitignore)
\`\`\`

---
*Report generated by report.sh*
EOF

echo -e "\nMarkdown report generated successfully: $OUTPUT_FILE"
